Web handlers
optimacros/applications_documentation pull request #18
Opened 2022-11-16 15:33 UTC by m-golovkina

- Plus some updates for diff.md
- Pictures were downscaled.

2022-11-17 09:37 UTC, iMoonGoose requested changes

2022-11-17 09:37 UTC, iMoonGoose commented on webHandlers/webHandlers.md
> +- `<HOST>` - адрес сервера, на котором установлена система Application Manager,
Здесь лучше придерживаться описания как на википедии https://ru.wikipedia.org/wiki/URL чтобы а) придерживаться стандартов, б) приучать людей к пониманию структуры URL

2022-11-17 09:37 UTC, iMoonGoose commented on diff.md
Надо переделать ссылку на `wss` протокол, она недавно поменялась для воркспейсов. Она на строке 41, но туда я коммент поставить не могу

2022-11-17 09:37 UTC, iMoonGoose commented on webHandlers/webHandlers.md
> +- `contentType` - тип переданного контента.
Надо добавить, какие `contentType` сейчас поддреживаются https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Content-Type https://ru.wikipedia.org/wiki/Список_MIME-типов

2022-11-21 11:41 UTC, m-golovkina commented on webHandlers/webHandlers.md
> +- `<HOST>` - адрес сервера, на котором установлена система Application Manager,
Исправлено

2022-11-21 11:42 UTC, m-golovkina commented on diff.md
Исправлено

2022-11-21 11:43 UTC, m-golovkina commented on webHandlers/webHandlers.md
> +- `contentType` - тип переданного контента.
Антон говорит поддерживаются все HTTP-методы и все Content-Types

2022-11-22 08:36 UTC, iMoonGoose approved these changes

2022-11-25 08:39 UTC, merged