Close connection with model
optimacros/applications_documentation pull request #22
Opened 2022-12-29 09:36 UTC by qx87

2022-12-29 16:30 UTC, m-golovkina requested changes

2022-12-29 16:30 UTC, m-golovkina commented on API/API.md
> +	close(): void;
Нужно так же добавить в файл-декларацию

2022-12-30 10:20 UTC, qx87 commented on API/API.md
> +	close(): void;
Оказывается, эта функция асинхронная. И вдобавок, существует функция OM.connectAsync(). Запросил у @Aggtaa уточнения. Когда сообщит, я добавлю.

2023-01-19 14:42 UTC, m-golovkina approved these changes

2023-01-19 14:42 UTC, merged