Async
optimacros/applications_documentation pull request #25
Opened 2022-12-30 11:19 UTC by qx87

Добавил описание первой проверенной рабочей асинхронной функции. Если всё хорошо, все следующие описания буду делать аналогично.

2023-01-18 13:42 UTC, m-golovkina requested changes

2023-01-18 13:42 UTC, m-golovkina commented on API/views.md
> +all(): (LabelsGroup | undefined)[]
или так должно быть? он разве может вернуть массив undefined?
```
all(): LabelsGroup[] | undefined
```

2023-01-18 13:42 UTC, m-golovkina commented on API/common.md
> +async autoCalcStatusAsync(): Promise<boolean>;
удали точку с запятой в конце

2023-01-18 13:42 UTC, m-golovkina commented on API/common.md
> +async autoCalcStatusAsync(): Promise<boolean>;
проверь все, я еще видела в других местах

2023-01-18 13:50 UTC, qx87 commented on API/views.md
> +all(): (LabelsGroup | undefined)[]
Я не знаю, такая стоит сигнатура функции. Видимо, может вернуть массив, где будут вперемешку LabelsGroup и undefined. Надо спрашивать у Антона. Но мне он и по более важным вопросам отвечает нечасто.

2023-01-18 14:01 UTC, qx87 commented on API/common.md
> +async autoCalcStatusAsync(): Promise<boolean>;
Всё исправил.

2023-01-19 12:36 UTC, m-golovkina requested changes

2023-01-19 12:36 UTC, m-golovkina commented on API/views.md
> +async createAsync(): Promise<Grid>;
Здесь точку с запятой в конце убрать

2023-01-19 12:36 UTC, m-golovkina commented on API/views.md
> +async allAsync(): Promise<(LabelsGroup | undefined)[]>;
Здесь точку с запятой в конце убрать

2023-01-19 12:36 UTC, m-golovkina commented on API/views.md
> +async getAsync(index: number): Promise<LabelsGroup | undefined>;
Здесь точку с запятой в конце убрать

2023-01-19 12:36 UTC, m-golovkina commented on API/views.md
> +	async columnsAsync(): Promise<LabelsGroup | undefined>;
ну и здесь тогда тоже отдели пробелами для красоты, как делал выше

2023-01-19 12:36 UTC, m-golovkina commented on API/views.md
> +async rowsAsync(): Promise<LabelsGroup | undefined>;
Здесь точку с запятой в конце убрать

2023-01-19 13:26 UTC, m-golovkina approved these changes

2023-01-19 13:26 UTC, merged